version: "1"

name: Portofolio-Saya
language: php

web:
  document_root: public

build:
  steps:
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

run:
  command: php artisan serve --host=0.0.0.0 --port=$PORT